<?php
/**
 * Plugin Name: Halkidiki Experience AI Planner V2
 * Description: Clean v2 bot flow for Halkidiki Experience.
 */
if (!defined('ABSPATH')) { define('ABSPATH', __DIR__ . '/'); }

function halkidiki_v2_norm($t){ $t=mb_strtolower(trim(strip_tags((string)$t)),'UTF-8'); return str_replace(['ά','έ','ή','ί','ό','ύ','ώ','ϊ','ΐ','ϋ','ΰ','ς'],['α','ε','η','ι','ο','υ','ω','ι','ι','υ','υ','σ'],$t); }
function halkidiki_v2_dataset(){ $p=__DIR__.'/halkidiki-places.json'; if(!file_exists($p)) return []; $d=json_decode(file_get_contents($p),true); return is_array($d)?$d:[]; }
function halkidiki_v2_region_aliases(){ return ['Πευκοχώρι'=>['πευκοχωρι','pefkochori','pefkohori'],'Άφυτος'=>['αφυτο','αφυτος','afytos','afitos'],'Καλλιθέα'=>['καλλιθεα','kallithea'],'Χανιώτη'=>['χανιωτη','hanioti','chanioti'],'Πολύχρονο'=>['πολυχρονο','polychrono'],'Κρυοπηγή'=>['κρυοπηγη','kriopigi'],'Παλιούρι'=>['παλιουρι','paliouri'],'Νέα Φώκεα'=>['νεα φωκεα','nea fokea'],'Νέα Ποτίδαια'=>['νεα ποτιδαια','nea potidaia'],'Σίβηρη'=>['σιβηρη','siviri'],'Σκάλα Φούρκας'=>['σκαλα φουρκασ','skala fourkas'],'Φούρκα'=>['φουρκα','fourka'],'Ποσείδι'=>['ποσειδι','poseidi'],'Καλάνδρα'=>['καλανδρα','kalandra'],'Αγία Παρασκευή'=>['αγια παρασκευη','agia paraskevi'],'Λουτρά'=>['λουτρα','loutra'],'Νέα Σκιώνη'=>['νεα σκιωνη','nea skioni'],'Μόλα Καλύβα'=>['μολα καλυβα','mola kalyva'],'Κασσάνδρα'=>['κασσανδρα','kassandra']]; }
function halkidiki_v2_detect_region($m){ $n=halkidiki_v2_norm($m); foreach(halkidiki_v2_region_aliases() as $c=>$a){ foreach($a as $x){ if(strpos($n,halkidiki_v2_norm($x))!==false) return $c; } } return ''; }
function halkidiki_v2_detect_intent($m){ $n=halkidiki_v2_norm($m); $map=['planner'=>['προγραμμα','πλανο','day plan','itinerary'],'smalltalk'=>['ευχαριστω','γεια','οκ','thanks'],'food'=>['φαω','φαγητο','εστιατοριο','ταβερνα','food','restaurant','lunch','dinner'],'coffee'=>['καφε','καφεδακι','coffee','cafe'],'drink'=>['ποτο','ποτα','κοκτειλ','cocktail','bar','μπαρ','nightlife'],'brunch'=>['brunch','πρωινο','breakfast'],'dessert'=>['κρεπα','γλυκο','παγωτο','dessert','ice cream','crepe'],'accommodation'=>['hotel','apartments','villa','διαμονη','δωματιο']]; foreach($map as $k=>$arr){ foreach($arr as $w){ if(strpos($n,halkidiki_v2_norm($w))!==false) return $k; } } return ''; }
function halkidiki_v2_nearby($r){ $m=['Άφυτος'=>['Καλλιθέα','Κρυοπηγή','Νέα Φώκεα'],'Καλλιθέα'=>['Άφυτος','Κρυοπηγή','Πολύχρονο'],'Πευκοχώρι'=>['Χανιώτη','Παλιούρι','Πολύχρονο'],'Χανιώτη'=>['Πολύχρονο','Πευκοχώρι','Κρυοπηγή'],'Παλιούρι'=>['Πευκοχώρι','Αγία Παρασκευή','Λουτρά','Χανιώτη']]; return $m[$r]??[]; }
function halkidiki_v2_allowed($intent){ $a=['food'=>['Εστιατόρια - Ταβέρνες','Εστιατόρια – Ταβέρνες','Fast Food','Snack Bar','Pizza & Pasta'],'coffee'=>['Cafe-Snacks','Cafe & Coctail','Cafe & Cocktail','Brunch','Snack Bar'],'drink'=>['Cafe & Coctail','Cafe & Cocktail','Beach Bars','Clubs','Bars'],'brunch'=>['Brunch','Cafe-Snacks','Snack Bar'],'dessert'=>['Παγωτό','Άρτος & Γλυκό','Cafe-Snacks','Brunch','Snack Bar'],'accommodation'=>['Apartments','Hotels','Luxury Suites','Studios','Villas']]; return $a[$intent]??[]; }
function halkidiki_v2_clean_desc($b,$intent,$region){ $name=html_entity_decode($b['name']??'',ENT_QUOTES|ENT_HTML5,'UTF-8'); $d=html_entity_decode(strip_tags($b['description']??''),ENT_QUOTES|ENT_HTML5,'UTF-8'); $d=trim(preg_replace('/^(to|το)?\s*'.preg_quote($name,'/').'\s*[-–—:,.]?\s*/iu','',$d)); $d=trim((preg_split('/[.!;;]/u',$d)[0]??'')); if($d===''||halkidiki_v2_norm($d)===halkidiki_v2_norm($name)){ $f=['food'=>"Καλή επιλογή για φαγητό στο {$region}.",'coffee'=>"Καλή επιλογή για καφέ στην περιοχή.",'drink'=>"Ιδανική επιλογή για ποτό ή έξοδο.",'brunch'=>"Ωραία επιλογή για brunch και χαλαρή στάση.",'dessert'=>"Ωραία επιλογή για γλυκό ή κρέπα.",'accommodation'=>"Καλή επιλογή για διαμονή στην περιοχή."]; return $f[$intent]??'Μια καλή επιλογή για αυτό που ζητάτε.'; } return $d; }
function halkidiki_v2_filter_items($items,$region,$intent){ $allow=halkidiki_v2_allowed($intent); $out=[]; foreach($items as $b){ $r=$b['region']??''; $cats=$b['categories']??[]; if(halkidiki_v2_norm($r)!==halkidiki_v2_norm($region)) continue; $ok=false; foreach($cats as $c){ foreach($allow as $a){ if(halkidiki_v2_norm($c)===halkidiki_v2_norm($a)) $ok=true; } } if($ok) $out[]=$b; } return $out; }
function halkidiki_v2_route($message,$pending,$planner){ $intent=halkidiki_v2_detect_intent($message); if($intent==='smalltalk') return ['route'=>'smalltalk']; if(!empty($planner['active'])) return ['route'=>'planner_reply']; if($intent==='planner') { $r=halkidiki_v2_detect_region($message); return ['route'=>$r?'planner_reply':'planner_clarification']; } $r=halkidiki_v2_detect_region($message); $i=in_array($intent,['food','coffee','drink','brunch','dessert','accommodation'],true)?$intent:''; if($r && !$i && !empty($pending['pending_intent'])) $i=$pending['pending_intent']; if(!$r && $i && !empty($pending['pending_region'])) $r=$pending['pending_region']; if($r&&$i) return ['route'=>'business_reply','region'=>$r,'intent'=>$i,'pending'=>['pending_region'=>'','pending_intent'=>'']]; if($r&&!$i) return ['route'=>'business_clarification','region'=>$r,'pending'=>['pending_region'=>$r,'pending_intent'=>'']]; if(!$r&&$i) return ['route'=>'business_clarification','intent'=>$i,'pending'=>['pending_region'=>'','pending_intent'=>$i]]; return ['route'=>'ai']; }
function halkidiki_v2_planner_reply($message,$items){ $region=halkidiki_v2_detect_region($message); if(!$region) return 'Από ποια περιοχή ξεκινάτε και τι ύφος θέλετε; παραλία, φαγητό, βόλτα ή βραδινή έξοδο;'; $ds=halkidiki_v2_dataset(); $beach=$ds['about_the_area']['beaches'][0]['name']??'μια κοντινή παραλία'; $att=$ds['about_the_area']['attractions'][0]['name']??'ένα σημείο ενδιαφέροντος'; $food=halkidiki_v2_filter_items($items,$region,'food'); $drink=halkidiki_v2_filter_items($items,$region,'drink'); $f=isset($food[0])?$food[0]['name']:'μια διαθέσιμη συνεργαζόμενη επιλογή'; $d=isset($drink[0])?$drink[0]['name']:'μια διαθέσιμη συνεργαζόμενη επιλογή'; return "Για μια όμορφη μέρα στο/στην {$region}, θα σας πρότεινα:\n\nΠρωί:\nΞεκινήστε με παραλία προς {$beach} και μια χαλαρή στάση για καφέ.\n\nΜεσημέρι:\nΓια φαγητό, μπορείτε να δείτε το {$f} και να συνεχίσετε με ξεκούραση κοντά στη θάλασσα.\n\nΑπόγευμα:\nΚάντε βόλτα και προσθέστε ένα σημείο ενδιαφέροντος όπως {$att}.\n\nΒράδυ:\nΚλείστε τη μέρα με ποτό ή έξοδο, για παράδειγμα στο {$d}.\n\nΑν θέλετε, μπορώ να το κάνω και πιο χαλαρό, πιο οικογενειακό ή πιο βραδινό."; }
